from typing import Protocol, Generator

from agio_pipe.base_classes.export_container import ExportContainerBase
from agio_pipe.entities.product import AProduct
from agio_pipe.entities.task import ATask


class PublishScene(Protocol):
    def save(self, file: str) -> str:...

    def load(self, file: str) -> str:...

    def get_export_container_class(self) -> object:...

    def create_container(self, name: str, task: ATask, product: AProduct, sources: list[str] = None, id: str = None,
        ) -> ExportContainerBase:...

    def create_scene_container(self, container: ExportContainerBase):...

    def remove_scene_container(self, container_id: str) -> ExportContainerBase|None:...

    def iter_scene_containers(self) -> Generator[ExportContainerBase, None, None]:...
